name: Build and Deploy
on:   
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: 286799714/vuepress-build-and-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.PERSONAL_SECRET }}
        TARGET_REPO: MCModderAnchor/tacwiki
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: |
          apt-get update
          pnpm add vuepress-theme-hope
          pnpm build
        BUILD_DIR: docs/.vuepress/dist/
        CNAME: tacwiki.mcma.club
