name: Build and Deploy
on:   
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.PERSONAL_SECRET }}
        TARGET_REPO: MCModderAnchor/tacwiki
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn create vuepress-theme-hope add docs && yarn run vuepress build docs
        BUILD_DIR: docs/.vuepress/dist/
        CNAME: tacwiki.mcma.club
